import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { logger } from './logger';

// ─── Configuration ────────────────────────────────────────────────────────

const CF_API = 'https://api.cloudflare.com/client/v4';

function isDryRun(): boolean {
  return !process.env.CLOUDFLARE_API_TOKEN || !process.env.CLOUDFLARE_ZONE_ID;
}

function cfApiToken(): string {
  const token = process.env.CLOUDFLARE_API_TOKEN;
  if (!token) {
    if (isDryRun()) return 'dry-run-token';
    throw new Error('CLOUDFLARE_API_TOKEN env var is required');
  }
  return token;
}

function cfZoneId(): string {
  const zoneId = process.env.CLOUDFLARE_ZONE_ID;
  if (!zoneId) {
    if (isDryRun()) return 'dry-run-zone';
    throw new Error('CLOUDFLARE_ZONE_ID env var is required');
  }
  return zoneId;
}

function serverIp(): string {
  return process.env.SERVER_IP ?? '84.235.239.6';
}

function baseDomain(): string {
  return process.env.NEXT_PUBLIC_BASE_DOMAIN ?? 'sinaicamps.com';
}

function nginxTenantsDir(): string {
  return process.env.NGINX_TENANTS_DIR ?? '/etc/nginx/tenants.d';
}

function adminEmail(): string {
  return process.env.ADMIN_EMAIL ?? 'admin@sinaicamps.com';
}

// ─── Cloudflare API ───────────────────────────────────────────────────────

async function cfFetch(method: string, path: string, body?: unknown): Promise<any> {
  if (isDryRun()) {
    logger.info(`[DomainProvisioning] DRY RUN: ${method} ${path}`);
    return {
      success: true,
      result: { id: `dry-${Date.now()}`, name: '', type: '', content: '' },
    };
  }
  const res = await fetch(`${CF_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${cfApiToken()}`,
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json();
  if (!json.success) {
    throw new Error(`Cloudflare API error: ${JSON.stringify(json.errors ?? json)}`);
  }
  return json;
}

// ─── DNS Record Management ────────────────────────────────────────────────

export async function createDnsRecord(
  type: 'A' | 'CNAME',
  name: string,
  content: string,
  proxied = true
): Promise<{ id: string }> {
  const zoneId = cfZoneId();
  const json = await cfFetch('POST', `/zones/${zoneId}/dns_records`, {
    type,
    name,
    content,
    ttl: 1,
    proxied,
  });
  const id: string = json.result.id;
  logger.info(`[DomainProvisioning] Created DNS ${type} record: ${name} → ${content} (id=${id})`);
  return { id };
}

export async function deleteDnsRecord(recordId: string): Promise<void> {
  const zoneId = cfZoneId();
  await cfFetch('DELETE', `/zones/${zoneId}/dns_records/${recordId}`);
  logger.info(`[DomainProvisioning] Deleted DNS record ${recordId}`);
}

export async function listDnsRecords(
  name?: string
): Promise<{ id: string; name: string; type: string; content: string }[]> {
  const zoneId = cfZoneId();
  const params = name ? `?name=${encodeURIComponent(name)}` : '';
  const json = await cfFetch('GET', `/zones/${zoneId}/dns_records${params}`);
  return json.result as any[];
}

// ─── Nginx Config Management ──────────────────────────────────────────────

export function writeNginxTenantConfig(domain: string, certPath: string, keyPath: string): void {
  if (isDryRun()) {
    logger.info(`[DomainProvisioning] DRY RUN: Skipping Nginx config write for ${domain}`);
    return;
  }
  const dir = nginxTenantsDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const config = `# Auto-generated by CampOps Domain Provisioning
server {
    listen 443 ssl http2;
    server_name ${domain} www.${domain};

    ssl_certificate ${certPath};
    ssl_certificate_key ${keyPath};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;

  const configPath = path.join(dir, `${domain}.conf`);
  fs.writeFileSync(configPath, config, 'utf-8');
  logger.info(`[DomainProvisioning] Wrote Nginx config: ${configPath}`);
}

export function removeNginxTenantConfig(domain: string): void {
  if (isDryRun()) {
    logger.info(`[DomainProvisioning] DRY RUN: Skipping Nginx config removal for ${domain}`);
    return;
  }
  const configPath = path.join(nginxTenantsDir(), `${domain}.conf`);
  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
    logger.info(`[DomainProvisioning] Removed Nginx config: ${configPath}`);
  }
}

export function reloadNginx(): void {
  if (isDryRun()) {
    logger.info('[DomainProvisioning] DRY RUN: Skipping Nginx reload');
    return;
  }
  try {
    execSync('sudo nginx -t 2>&1', { stdio: 'pipe' });
    execSync('sudo systemctl reload nginx', { stdio: 'pipe' });
    logger.info('[DomainProvisioning] Nginx reloaded successfully');
  } catch (err: any) {
    const msg = err.stderr?.toString() ?? err.message;
    throw new Error(`Nginx reload failed: ${msg}`);
  }
}

// ─── Let's Encrypt (Certbot) ──────────────────────────────────────────────

function provisionLetsEncrypt(domain: string): { certPath: string; keyPath: string } | null {
  if (isDryRun()) {
    logger.info(`[DomainProvisioning] DRY RUN: Skipping cert provisioning for ${domain}`);
    return {
      certPath: '/etc/letsencrypt/live/example/fullchain.pem',
      keyPath: '/etc/letsencrypt/live/example/privkey.pem',
    };
  }
  const certDir = `/etc/letsencrypt/live/${domain}`;
  const certPath = `${certDir}/fullchain.pem`;
  const keyPath = `${certDir}/privkey.pem`;

  if (fs.existsSync(certPath)) {
    logger.info(`[DomainProvisioning] Cert already exists for ${domain}, skipping`);
    return { certPath, keyPath };
  }

  try {
    execSync(
      `sudo certbot certonly --standalone --preferred-challenges http ` +
        `-d ${domain} -d www.${domain} ` +
        `--non-interactive --agree-tos --email ${adminEmail()} ` +
        `--http-01-port 8888 2>&1`,
      { stdio: 'pipe', timeout: 90000 }
    );
    logger.info(`[DomainProvisioning] Let's Encrypt cert provisioned for ${domain}`);
    return { certPath, keyPath };
  } catch (err: any) {
    logger.warn(`[DomainProvisioning] Certbot failed for ${domain}: ${err.message}`);
    return null;
  }
}

function removeLetsEncrypt(domain: string): void {
  if (isDryRun()) {
    logger.info(`[DomainProvisioning] DRY RUN: Skipping cert deletion for ${domain}`);
    return;
  }
  try {
    execSync(`sudo certbot delete --cert-name ${domain} --non-interactive 2>&1`, { stdio: 'pipe' });
  } catch {}
}

// ─── High-level Provisioning Flows ────────────────────────────────────────

export interface ProvisioningResult {
  success: boolean;
  dnsRecordId?: string;
  error?: string;
}

/**
 * Provision a Premium subdomain (slug.BASE_DOMAIN).
 * Creates a CNAME DNS record — SSL handled by Cloudflare wildcard cert.
 */
export async function provisionSubdomain(
  slug: string,
  _siteId: string
): Promise<ProvisioningResult> {
  const hostname = `${slug}.${baseDomain()}`;
  try {
    const existing = await listDnsRecords(hostname);
    if (existing.length > 0) {
      logger.info(`[DomainProvisioning] DNS record already exists for ${hostname}, skipping`);
      return { success: true, dnsRecordId: existing[0].id };
    }
    const record = await createDnsRecord('CNAME', hostname, baseDomain(), true);
    return { success: true, dnsRecordId: record.id };
  } catch (err: any) {
    logger.error(`[DomainProvisioning] Subdomain provisioning failed: ${err.message}`);
    return { success: false, error: err.message };
  }
}

/**
 * Provision an Ultimate custom domain.
 * 1. Create A record in Cloudflare DNS
 * 2. Provision Let's Encrypt cert
 * 3. Write Nginx config
 * 4. Reload Nginx
 */
export async function provisionCustomDomain(
  domain: string,
  _siteId: string
): Promise<ProvisioningResult> {
  const ip = serverIp();
  let dnsRecordId: string | undefined;

  try {
    const existing = await listDnsRecords(domain);
    if (existing.length > 0) {
      dnsRecordId = existing[0].id;
      logger.info(`[DomainProvisioning] DNS record already exists for ${domain}, skipping`);
    } else {
      const record = await createDnsRecord('A', domain, ip, true);
      dnsRecordId = record.id;
    }
  } catch (err: any) {
    return { success: false, error: `DNS provisioning failed: ${err.message}` };
  }

  const cert = provisionLetsEncrypt(domain);
  if (!cert) {
    return {
      success: true,
      dnsRecordId,
      error:
        'DNS provisioned but SSL failed (domain will work with HTTP-only or Cloudflare Flexible)',
    };
  }

  try {
    writeNginxTenantConfig(domain, cert.certPath, cert.keyPath);
    reloadNginx();
  } catch (err: any) {
    return { success: false, dnsRecordId, error: `Nginx config failed: ${err.message}` };
  }

  return { success: true, dnsRecordId };
}

/**
 * Remove all provisioning for a domain (plan downgrade / deletion).
 */
export async function removeDomainProvisioning(
  domain: string,
  dnsRecordId?: string | null
): Promise<boolean> {
  try {
    if (dnsRecordId) {
      await deleteDnsRecord(dnsRecordId);
    } else {
      const records = await listDnsRecords(domain);
      for (const r of records) {
        if (r.content === serverIp() || r.name === domain) {
          await deleteDnsRecord(r.id);
        }
      }
    }
  } catch (err: any) {
    logger.warn(`[DomainProvisioning] DNS cleanup warning: ${err.message}`);
  }

  removeNginxTenantConfig(domain);
  removeLetsEncrypt(domain);

  try {
    reloadNginx();
  } catch {}

  return true;
}

export async function removeSubdomainProvisioning(
  slug: string,
  dnsRecordId?: string | null
): Promise<boolean> {
  const hostname = `${slug}.${baseDomain()}`;
  return removeDomainProvisioning(hostname, dnsRecordId);
}
